# Yeh rule Netlify ko batata hai ki har request ko index.html par bhejo
# Taaki /random jaisa custom URL kaam kar sake
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Yeh naya section Netlify ko placeholders replace karne ke liye bolta hai
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = false
[build.processing.js]
  bundle = false
  minify = false
[build.processing.html]
  pretty_urls = false
[build.processing.images]
  compress = false
